spring:
  rabbitmq:
    host: 127.0.0.1
    port: 5672
    username: chen
    password: 123456
    virtual-host: chen
    #发布消息成功到交换器后会触发回调方法  手动
    publisher-confirm-type: correlated
    #回退接口
    publisher-returns: true
    listener:
      direct:
        #限流  手动确认
        prefetch: 1  # 每次只能获取一条消息，处理完成才能获取下一个消息
        acknowledge-mode: manual  # 签收模式为手动签收-那么需要在代码中手动ACK
        # 拒绝消息是否重回队列
        default-requeue-rejected: true

    #集群配置
    #addresses:


server:
  servlet:
    context-path: /
  port: 8082




